### PR TITLE
Fix static resources loading

### PR DESCRIPTION
**Pull request by Mikiya83**
Align urls.py with autotest version

#424

### CODE REVIEW

**Comment by constantinius** [comment]
Hi @Mikiya83 

Thanks for the patch. I had to research myself, but in the back of my head there was something why this was not enabled. The reason is that this `static` file serving is only suitable for [development, and not for production](https://docs.djangoproject.com/en/3.0/howto/static-files/#serving-static-files-during-development). This is the reason why it is not enabled in default instances. 

The usual approach is to do a `collectstatic` and expose that directoy in your webserver (Apache, nginx, etc). 
In the default docker images we use `gunicorn`, which does not provide a way to serve static files, so there it is still an unsolved issue.

**Comment by Mikiya83** [comment]
Ok, indeed if gunicorn is not the "recommended" web server to use, this pull is not necessary, but it could be cool if the default docker image can use static files (without css files it's not very user-friendly ;) )

**Comment by constantinius** [comment]
Indeed! Also, other parts like the web-client which rely on static files will not work at all. But using the `static` function in production seems to be discouraged by the Django devs.

Maybe we can add it behind the `DEBUG` flag like in this [article](https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/)?

```python
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
```

**Comment by Mikiya83** [comment]
Why not, it's a good compromise to use DEBUG flag for that !

**Comment by constantinius** [comment]
Superseded by #469

**Pull request closed without merging**
