### PR TITLE
DAMATS branch merge

### PR DESCRIPTION
**Pull request by pacesm**
The DAMATS project is over and it it time to get rid of the project branch.

Most of the features introduced in DAMATS were already merged trough various feature branches. The only remaining thing is a small change in the WMS handler allowing access to all request parameters from the layer factories.

DAMATS implements its own layer factories allowing display of the change detection and classification results. These factories sometime need specific parameters in addition to the standard WMS. This change then allows the layer factories to see these additional parameters.

### CODE REVIEW

**Comment by pacesm** [comment]
test this please

**Comment by Schpidi** [comment]
test this please

**Comment by Schpidi** [comment]
test this please

**Comment by Schpidi** [comment]
test this please

**Comment by Schpidi** [comment]
test this please

**Comment by Schpidi** [comment]
test this please

**Pull request merged**
