### PR TITLE
Adding option to update range-type by the eoxs_rangetype_load command.

### PR DESCRIPTION
**Pull request by pacesm**
So far the `eoxs_rangetype_load` command allowed only creation of new range-types. But often the range types need to be updated and this was not possible via the CLI. Therefore a new option was added to the CLI command which allows update of an existing range type.

In addition, I reviewed the  `eoxs_rangetype_load` and  `eoxs_rangetype_list` commands and cleaned and re-factored the old messy code.

### CODE REVIEW

**Comment by pacesm** [comment]
@Schpidi: Can you please have a look on the failed Jenkins tests? The failure does not seem to be caused by the tested commits.

**Comment by Schpidi** [comment]
retest this please

**Comment by Schpidi** [comment]
retest this please

**Comment by Schpidi** [comment]
retest this please

**Comment by Schpidi** [comment]
retest this please

**Comment by Schpidi** [comment]
Jenkins works again, not sure why old tests are shown here though.

**Comment by pacesm** [comment]
A new commit should flush the pipes.

**Comment by pacesm** [comment]
This pull request has been open for more than two weeks now. All tests passing and since I have not received any objection I assume the pull request is cleared to be merged.
I need this feature for the VirES Sun_dB  update.

**Comment by constantinius** [comment]
This PR seems fine and the tests pass, so I'm all in favor of merging.

**Pull request merged**
