### PR TITLE
fixed bug to query by parent product

### PR DESCRIPTION
**Pull request by jankovicgd**

### CODE REVIEW

**Review by totycro — APPROVED** [review]
So does this mean that the footprint field of the `Coverage` model isn't valid? If so, maybe we can remove the field.

**Comment by jankovicgd** [comment]
It is valid, its maybe designed a bit weirdly, since you can have coverages that don't share the footprint but share a single product.

**Comment by jankovicgd** [comment]
@lubojr @constantinius not sure where this edge case appears. Perhaps a table with footprints and the footprints in `Coverage` and `Product` could be foreign keys to avoid duplication. Although when writing queries such as in this case its not immediately obvious which one to use.

**Comment by lubojr** [comment]
The fix should take parent product footprint only if coverage footprint is null (as a generic fix)

**Comment by jankovicgd** [comment]
The query may use some advanced logic, and for our use case at the moment it may not be necessary, added reminder and merging

**Pull request merged**
